// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz3Cw8xEFFCWwZX9gWiIYAg0AUz2FGOsI',
    appId: '1:772267063346:web:1bdc4b5d81f3e406c5e42b',
    messagingSenderId: '772267063346',
    projectId: 'dextercart-aa4e6',
    authDomain: 'dextercart-aa4e6.firebaseapp.com',
    storageBucket: 'dextercart-aa4e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Ux_7NFlMht3BHAjNqmVaBGYazr7teQw',
    appId: '1:772267063346:android:5ad3b1fcd7ee550ac5e42b',
    messagingSenderId: '772267063346',
    projectId: 'dextercart-aa4e6',
    storageBucket: 'dextercart-aa4e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA79tNPgyP1zg_-RVz6dt70mn9qPOHcqG4',
    appId: '1:772267063346:ios:67e6ad67153c547fc5e42b',
    messagingSenderId: '772267063346',
    projectId: 'dextercart-aa4e6',
    storageBucket: 'dextercart-aa4e6.appspot.com',
    androidClientId: '772267063346-pchqitisnl8655a7r4pphub948llqtej.apps.googleusercontent.com',
    iosClientId: '772267063346-84q8450cmo5k7tiehfa48iq95q7ng0ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.dexterCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA79tNPgyP1zg_-RVz6dt70mn9qPOHcqG4',
    appId: '1:772267063346:ios:67e6ad67153c547fc5e42b',
    messagingSenderId: '772267063346',
    projectId: 'dextercart-aa4e6',
    storageBucket: 'dextercart-aa4e6.appspot.com',
    androidClientId: '772267063346-pchqitisnl8655a7r4pphub948llqtej.apps.googleusercontent.com',
    iosClientId: '772267063346-84q8450cmo5k7tiehfa48iq95q7ng0ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.dexterCart',
  );
}
